### ISSUE TITLE
`ImportError` on `pip install`

### ISSUE THREAD

**Issue by fvanmaele** [conda-forge/pip-feedstock#119]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When using `pip install`, I get the following error on `osx-arm64`
```
% pip install
Traceback (most recent call last):
  File "/opt/miniconda3/bin/pip", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/pip/_internal/cli/main.py", line 77, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/pip/_internal/commands/__init__.py", line 114, in create_command
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/miniconda3/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 15, in <module>
    from pip._internal.cli.req_command import (
  File "/opt/miniconda3/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 21, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/opt/miniconda3/lib/python3.12/site-packages/pip/_internal/index/package_finder.py", line 30, in <module>
    from pip._internal.req import InstallRequirement
  File "/opt/miniconda3/lib/python3.12/site-packages/pip/_internal/req/__init__.py", line 8, in <module>
    from .req_install import InstallRequirement
  File "/opt/miniconda3/lib/python3.12/site-packages/pip/_internal/req/req_install.py", line 40, in <module>
    from pip._internal.operations.install.wheel import install_wheel
  File "/opt/miniconda3/lib/python3.12/site-packages/pip/_internal/operations/install/wheel.py", line 39, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/opt/miniconda3/lib/python3.12/site-packages/pip/_vendor/distlib/scripts.py", line 16, in <module>
    from .compat import sysconfig, detect_encoding, ZipFile
  File "/opt/miniconda3/lib/python3.12/site-packages/pip/_vendor/distlib/compat.py", line 81, in <module>
    import xmlrpc.client as xmlrpclib
  File "/opt/miniconda3/lib/python3.12/xmlrpc/client.py", line 138, in <module>
    from xml.parsers import expat
  File "/opt/miniconda3/lib/python3.12/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: dlopen(/opt/miniconda3/lib/python3.12/lib-dynload/pyexpat.cpython-312-darwin.so, 0x0002): Symbol not found: _XML_SetReparseDeferralEnabled
  Referenced from: <32D45E4C-EE22-353E-9FF6-B4E52DDAAE5B> /opt/miniconda3/lib/python3.12/lib-dynload/pyexpat.cpython-312-darwin.so
  Expected in:     <F228183A-3E96-30B4-A12D-CF9430D458FB> /usr/lib/libexpat.1.dylib
```

### Installed packages

```shell
# packages in environment at /opt/miniconda3:
#
# Name                    Version                   Build  Channel
anaconda-anon-usage       0.4.4           py312hd6b623d_100  
archspec                  0.2.3              pyhd8ed1ab_0    conda-forge
astra-toolbox             2.1.2           py312h1aa2ef4_1    conda-forge
boltons                   24.0.0             pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hb547adb_1    conda-forge
brotli-bin                1.1.0                hb547adb_1    conda-forge
brotli-python             1.1.0           py312h9f69965_1    conda-forge
bzip2                     1.0.8                h93a5062_5    conda-forge
c-ares                    1.28.1               h93a5062_0    conda-forge
ca-certificates           2024.7.4             hf0a4a13_0    conda-forge
cctools                   986                  h4c9edd9_0    conda-forge
cctools_osx-arm64         986                  hd11630f_0    conda-forge
certifi                   2024.6.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py312h8e38eb3_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
clang                     18.1.3          default_h4cf2255_0    conda-forge
clang-18                  18.1.3          default_he012953_0    conda-forge
clang_impl_osx-arm64      18.1.3              hda94301_11    conda-forge
clang_osx-arm64           18.1.3              h54d7cd3_11    conda-forge
clangxx                   18.1.3          default_h4cf2255_0    conda-forge
cmake                     3.29.2               h50fd54c_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
compiler-rt               18.1.3               h3808999_0    conda-forge
compiler-rt_osx-arm64     18.1.3               h3808999_0    conda-forge
conda                     24.5.0          py312h81bd7bf_0    conda-forge
conda-content-trust       0.2.0              pyhd8ed1ab_0    conda-forge
conda-libmamba-solver     24.1.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.3.0              pyh7900ff3_0    conda-forge
conda-package-streaming   0.10.0             pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1           py312h0fef576_0    conda-forge
cryptography              42.0.8          py312had01cb0_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
distro                    1.9.0              pyhd8ed1ab_0    conda-forge
fftw                      3.3.10          mpi_mpich_h0cb5807_9    conda-forge
fmt                       10.2.1               h2ffa867_0    conda-forge
fonttools                 4.53.0          py312h7e5086c_0    conda-forge
freetype                  2.12.1               hadb7bae_2    conda-forge
frozendict                2.4.4           py312h7e5086c_0    conda-forge
gfortran                  13.2.0               h1ca8e4b_1    conda-forge
gfortran_impl_osx-arm64   13.2.0               h252ada1_3    conda-forge
gfortran_osx-arm64        13.2.0               h57527a5_1    conda-forge
gmp                       6.3.0                hebf3989_1    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hdf5                      1.14.3          mpi_mpich_h460762b_1    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
hypre                     2.31.0          mpi_mpich_hb9ad4ab_0    conda-forge
icu                       73.2                 hc8870d7_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
isl                       0.26            imath32_h347afa1_101    conda-forge
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
jsonpointer               3.0.0           py312h81bd7bf_0    conda-forge
kiwisolver                1.4.5           py312h389731b_1    conda-forge
krb5                      1.21.3               h237132a_0    conda-forge
lcms2                     2.16                 ha0e7c42_0    conda-forge
ld64                      711                  h4c6efb1_0    conda-forge
ld64_osx-arm64            711                  h5e7191b_0    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libaec                    1.1.3                hebf3989_0    conda-forge
libarchive                3.7.2                hcacb583_1    conda-forge
libastra                  2.1.2                hd8cd87f_2    conda-forge
libblas                   3.9.0           22_osxarm64_openblas    conda-forge
libbrotlicommon           1.1.0                hb547adb_1    conda-forge
libbrotlidec              1.1.0                hb547adb_1    conda-forge
libbrotlienc              1.1.0                hb547adb_1    conda-forge
libcblas                  3.9.0           22_osxarm64_openblas    conda-forge
libclang-cpp18.1          18.1.3          default_he012953_0    conda-forge
libcurl                   8.7.1                h2d989ff_0    conda-forge
libcxx                    17.0.6               h0812c0d_3    conda-forge
libdeflate                1.20                 h93a5062_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h93a5062_2    conda-forge
libexpat                  2.6.2                hebf3989_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_3    conda-forge
libgfortran-devel_osx-arm64 13.2.0               h5d7a38c_3    conda-forge
libgfortran5              13.2.0               hf226fd6_3    conda-forge
libhwloc                  2.10.0          default_h52d8fe8_1000    conda-forge
libiconv                  1.17                 h0d3ecfb_2    conda-forge
libjpeg-turbo             3.0.0                hb547adb_1    conda-forge
liblapack                 3.9.0           22_osxarm64_openblas    conda-forge
libllvm18                 18.1.3               h30cc82d_0    conda-forge
libmamba                  1.5.8                h90c426b_0    conda-forge
libmambapy                1.5.8           py312h344e357_0    conda-forge
libnghttp2                1.58.0               ha4dd798_1    conda-forge
libopenblas               0.3.27          openmp_h6c19121_0    conda-forge
libpng                    1.6.43               h091b4b1_0    conda-forge
libptscotch               7.0.4                h44b462d_5    conda-forge
libscotch                 7.0.4                h75850e6_5    conda-forge
libsolv                   0.7.29               h1efcc80_0    conda-forge
libsqlite                 3.46.0               hfb93653_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libtiff                   4.6.0                h07db509_3    conda-forge
libuv                     1.48.0               h93a5062_0    conda-forge
libwebp-base              1.4.0                h93a5062_0    conda-forge
libxcb                    1.16                 hf2054a2_0    conda-forge
libxml2                   2.12.7               ha661575_1    conda-forge
libzlib                   1.3.1                h0d3ecfb_0    conda-forge
llvm-openmp               18.1.8               hde57baf_0    conda-forge
llvm-tools                18.1.3               h30cc82d_0    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
lzo                       2.10              h93a5062_1001    conda-forge
matplotlib                3.8.4           py312h1f38498_2    conda-forge
matplotlib-base           3.8.4           py312ha6faf65_0    conda-forge
menuinst                  2.1.1           py312h81bd7bf_0    conda-forge
metis                     5.1.0             h13dd4ca_1007    conda-forge
mpc                       1.3.1                h91ba8db_0    conda-forge
mpfr                      4.2.1                h41d338b_1    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     4.2.2              h9ee2227_100    conda-forge
mumps-include             5.7.2                hce30654_0    conda-forge
mumps-mpi                 5.7.2                hd0c33d2_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.5                  hb89a1cb_0    conda-forge
numpy                     1.26.4          py312h8442bc7_0    conda-forge
openjpeg                  2.5.2                h9f1df11_0    conda-forge
openssl                   3.3.1                hfb2fe0b_1    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py312h88edd18_0    conda-forge
parmetis                  4.0.3             hefa2a9d_1005    conda-forge
petsc                     3.21.3          real_hb21bb17_100    conda-forge
petsc4py                  3.21.0          real_hc48b7db_101    conda-forge
pillow                    10.4.0          py312h39b1d8d_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
plotly                    5.22.0             pyhd8ed1ab_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6           py312h02f2b3b_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pylops                    2.2.0              pyhd8ed1ab_1    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyproximal                0.7.0              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.12.4          h30c5eda_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python.app                1.4             py312h7fd2b6f_3    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
reproc                    14.2.4.post0         h93a5062_1    conda-forge
reproc-cpp                14.2.4.post0         h965bd2d_1    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rhash                     1.4.4                hb547adb_0    conda-forge
ruamel.yaml               0.18.6          py312he37b823_0    conda-forge
ruamel.yaml.clib          0.2.8           py312he37b823_0    conda-forge
scalapack                 2.2.0                hb170938_1    conda-forge
scikit-learn              1.4.2           py312hd4306f4_0    conda-forge
scipy                     1.14.0          py312h14ffa8f_0    conda-forge
setuptools                70.1.1             pyhd8ed1ab_0    conda-forge
sigtool                   0.1.3                h44b9a77_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
suitesparse               7.7.0                hf6fcff2_1    conda-forge
superlu                   5.2.2                hc615359_0    conda-forge
superlu_dist              9.0.0                h2cb61f8_1    conda-forge
tapi                      1100.0.11            he4954df_0    conda-forge
tbb                       2021.12.0            h2ffa867_0    conda-forge
tenacity                  8.4.2              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
tornado                   6.4.1           py312h7e5086c_0    conda-forge
tqdm                      4.66.4             pyhd8ed1ab_0    conda-forge
truststore                0.8.0              pyhd8ed1ab_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
yaml-cpp                  0.8.0                h13dd4ca_0    conda-forge
zlib                      1.3.1                h0d3ecfb_0    conda-forge
zstandard                 0.22.0          py312h7975427_0    conda-forge
zstd                      1.5.5                h4f39d0f_0    conda-forge
```

### Environment info

```shell
active environment : base
    active env location : /opt/miniconda3
            shell level : 1
       user config file : /Users/fvanmaele/.condarc
 populated config files : /Users/fvanmaele/.condarc
          conda version : 24.5.0
    conda-build version : not installed
         python version : 3.12.4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.5.0=0
                          __unix=0=0
       base environment : /opt/miniconda3  (writable)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/miniconda3/pkgs
                          /Users/fvanmaele/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /Users/fvanmaele/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.5.0 requests/2.32.3 CPython/3.12.4 Darwin/23.5.0 OSX/ solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by fvanmaele** [comment]
https://github.com/conda-forge/expat-feedstock/issues/48
