### ISSUE TITLE
Version 21.2.1 breaks "-r file:" identifiers

### ISSUE THREAD

**Issue by mfansler** [conda-forge/pip-feedstock#76]
**StackOverflow:** https://stackoverflow.com/q/68571543/570918 

## Overview
Using a `file:` identifier in `pip install -r` commands results in `FileNotFoundError` error. This only appears to impact `pip==21.2.1`. Removing the `file:` identifier resolves issue.

# Reproduce

## Files
**env.yaml**
```yaml
name: foo
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=21.2.1
  - pip:
    - -r file:requirements.txt
```

**requirements.txt**
```tsv
numpy
```

## Commands

```bash
conda env create -f env.yaml
```

## Result
```bash
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['/Users/mfansler/miniconda3/envs/foo/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/mfansler/scratch/req/condaenv.kodk0gvc.requirements.txt']
Pip subprocess output:

Pip subprocess error:
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/mfansler/miniconda3/envs/foo/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/Users/mfansler/miniconda3/envs/foo/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/Users/mfansler/miniconda3/envs/foo/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 286, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/Users/mfansler/miniconda3/envs/foo/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 384, in get_requirements
    for parsed_req in parse_requirements(
  File "/Users/mfansler/miniconda3/envs/foo/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 135, in parse_requirements
    for parsed_line in parser.parse(filename, constraint):
  File "/Users/mfansler/miniconda3/envs/foo/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 319, in parse
    yield from self._parse_and_recurse(filename, constraint)
  File "/Users/mfansler/miniconda3/envs/foo/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 348, in _parse_and_recurse
    yield from self._parse_and_recurse(req_path, nested_constraint)
  File "/Users/mfansler/miniconda3/envs/foo/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 324, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "/Users/mfansler/miniconda3/envs/foo/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 353, in _parse_file
    _, content = get_file_content(filename, self._session)
  File "/Users/mfansler/miniconda3/envs/foo/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 518, in get_file_content
    resp = session.get(url)
  File "/Users/mfansler/miniconda3/envs/foo/lib/python3.9/site-packages/pip/_vendor/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Users/mfansler/miniconda3/envs/foo/lib/python3.9/site-packages/pip/_internal/network/session.py", line 454, in request
    return super().request(method, url, *args, **kwargs)
  File "/Users/mfansler/miniconda3/envs/foo/lib/python3.9/site-packages/pip/_vendor/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/mfansler/miniconda3/envs/foo/lib/python3.9/site-packages/pip/_vendor/requests/sessions.py", line 697, in send
    r.content
  File "/Users/mfansler/miniconda3/envs/foo/lib/python3.9/site-packages/pip/_vendor/requests/models.py", line 836, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/Users/mfansler/miniconda3/envs/foo/lib/python3.9/site-packages/pip/_vendor/requests/models.py", line 769, in generate
    chunk = self.raw.read(chunk_size)
AttributeError: 'FileNotFoundError' object has no attribute 'read'
|
failed

CondaEnvException: Pip failed
```

## Temporary Workarounds

Leaving out the `file:` identifier works:

**env.yaml**
```yaml
name: foo
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=21.2.1
  - pip:
    - -r requirements.txt
```

Alternatively, previous version works:

**env.yaml**
```yaml
name: foo
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=21.1.3
  - pip:
    - -r file:requirements.txt
```

## Additional Comments

This is likely an upstream issue, but at the least this can serve as a note on the release for others who may encounter it.

**Comment by mfansler** [comment]
Upstream issue, for reference: https://github.com/pypa/pip/issues/10237

**Comment by mfansler** [comment]
This is effectively resolved. Users should permanently adopt the first workaround, i.e.,

```yaml
  - pip:
    - -r file:requirements.txt
```

should be 

```yaml
  - pip:
    - -r requirements.txt
```
